---
title: "My Wild Website"
author: "Cezanna"
date: "10/10/2019"
output:
  html_document: default
  pdf_document: default
---

```{r}
library(dplyr)
library(tidyr)
library(ggplot2)

```


```{r}
esc <- read.csv("https://knb.ecoinformatics.org/knb/d1/mn/v2/object/urn%3Auuid%3Af119a05b-bbe7-4aea-93c6-85434dcb1c5e", stringsAsFactors = F)
```

```{r}
annual_esc <- esc %>% 
  separate(sampleDate, c("Year", "Month", "Day"), sep = "-", remove = F)

head(annual_esc)
  
```

```{r}
species_list <- c("Chinook", "Sockeye", "Chum", "Pink", "Coho")

annual_esc <- esc %>% 
  separate(sampleDate, c("Year", "Month", "Day"), sep = "-", remove = F) %>% 
  mutate(Year = as.numeric(Year)) %>% 
  group_by(Year, SASAP.Region, Species) %>% 
  summarise(total_escapement = sum(DailyCount)) %>% 
  filter(Species %in% c(species_list))



head(annual_esc)
```

# Visualize Escapement
aes stands for aesthetics! this has to do with the structure of the plot, not the actual aesthetics of the plot. LOL. 

```{r}
ggplot(data = annual_esc, mapping = aes(x = Species, y = total_escapement, fill = SASAP.Region)) + 
  geom_col()
```


